# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84c0b464f0f43d32eaa0bdf8070b9f530eb207163abca2b725efd4c84cbe2552a23e571b8f16473b2028f5d7f3bb43cc0914efaf41ea5d463d372dce8e3aa083

test:
  secret_key_base: 01fbfa1f795ced2e06395b3cfbda5debcfd8ef44f271b1dab3f40cdf05ff72c2276115bd4f0a8ee911058bf62a529e767ad5c4ddcd3d3254e74dd474bb986e6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
